import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import { CartProvider } from "@/context/CartContext";
import AOSProvider from "@/animations/AOSProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TS One",
  description: "Generated by next-ts app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <CartProvider>
          <AOSProvider />
          <Header brandName="TS One" />
          <main className="px-4 py-8">
            {children}
          </main>
          <Footer
            brandName="TS One"
            email="example@email.com"
            phone="+880 1234-567890"
            address="Dhaka, Bangladesh"
          />
        </CartProvider>
      </body>
    </html>
  );
}
